### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by SaintLogos1234** [wzzheng/HDML#1]
I used the code you provided to download the dataset and the following problems occurred：
Traceback (most recent call last):
  File "datasets/cars196_downloader.py", line 15, in <module>
    fuel_root_path = fuel.config.config["data_path"]["yaml"]
KeyError: 'yaml'

**Comment by wzzheng** [comment]
Hi, I'll look into the problem. Maybe right now the best way is to download directly from the website https://ai.stanford.edu/~jkrause/cars/car_dataset.

**Comment by SaintLogos1234** [comment]
thank you for your reply
