### ISSUE TITLE
Configuration on SOP dataset

### ISSUE THREAD

**Issue by kdhht2334** [wzzheng/HDML#14]
Hi, i'm training your source code now. In Cars196 and CUB200-2011 it works well.

But recall rate of SOP (stanford online products) is not same as paper's one.

Even though I have experimented with changing the configuration several times, only bad results.

So if you have free time, please let me know the configuration on SOP dataset.

Thanks!

**Comment by wzzheng** [comment]
Hi, sorry for the late reply. The SOP dataset is a little bit tricky due to its large size. I will recently rearrange the codes and add configurations for the SOP dataset.

**Comment by kdhht2334** [comment]
Thank's for reply.
I'll try it after uploading newly released version 👍
