### ISSUE TITLE
Inferences

### ISSUE THREAD

**Issue by thaiat** [wzzheng/HDML#2]
Hi, and thks for this repo 
Could you provide some guidances on running inferences when the model is trained ?

**Comment by wzzheng** [comment]
Hi, you can load the trained model by restoring the checkpoint  (set FLAGS.load_formalVal = True), and then compute embedding_z with your data (something like sess.run([embedding_z])). You can use the embeddings to do your own tasks.

We will try to add inference codes for easy use.

**Comment by batrlatom** [comment]
@wzzheng Is there any easy inference code as you mentioned earlier?
