### ISSUE TITLE
[Maths] Symbol in the paper?

### ISSUE THREAD

**Issue by stoneyang** [wzzheng/HDML#4]
Hi, @wzzheng , 

Thanks for your contribution of this repo, and the original work. 

In reading your paper, I found something that might be typo:

1. In the 3rd paragraph in Sec. 3.2, you name the `augmented harder negative sample` as **z with a tilde above it and a minus as a script**, while in the append maths formulation (ie, eq.4) and the remaining of this section, I could not find any other symbol like this. 
2. In the 1st paragraph in Sec. 3.3, there is another **z with a tilde above it and a minus as a script,** again, I still could not find any other symbol like this in the same section, but only **z with a tilde above it without any script** in the 4th paragraph in the same section. 

Is this just a typo, or something not fully rendered?

**Comment by KimiGranger** [comment]
Hi, thanks for your interests in our work! We apologize for the typos and will correct them in the next arxiv version. To answer your question, 
1. The symbol of **augmented harder negative sample** should be **z with a hat above it and a minus as a script** as in eq.4. 
2. It should also be **z with a hat above it and a minus as a script**. Also, in the 5th line of the 4th paragraph, the **z with a tilde above it** should be **z with a hat above it**. 

You can see Figure 1 for an illustration of those symbols. Intuitively, symbols with a hat refer to augmented feature/embeddings, and symbols with a tilde refer to synthesized feature/embeddings.

I hope you can understand the symbols even though I admit they are a bit confusing:(.  You are welcomed to ask any further questions.

Thanks again!

**Comment by wzzheng** [comment]
Hi, thanks for your interests in our work! We apologize for the typos and will correct them in the next arxiv version. To answer your question, 
1. The symbol of **augmented harder negative sample** should be **z with a hat above it and a minus as a script** as in eq.4. 
2. It should also be **z with a hat above it and a minus as a script**. Also, in the 5th line of the 4th paragraph, the **z with a tilde above it** should be **z with a hat above it**. 

You can see Figure 1 for an illustration of those symbols. Intuitively, symbols with a hat refer to augmented feature/embeddings, and symbols with a tilde refer to synthesized feature/embeddings.

I hope you can understand the symbols even though I admit they are a bit confusing:(.  You are welcomed to ask any further questions.

Thanks again!

**Comment by stoneyang** [comment]
> Hi, thanks for your interests in our work! We apologize for the typos and will correct them in the next arxiv version. To answer your question,
> 
> 1. The symbol of **augmented harder negative sample** should be **z with a hat above it and a minus as a script** as in eq.4.
> 2. It should also be **z with a hat above it and a minus as a script**. Also, in the 5th line of the 4th paragraph, the **z with a tilde above it** should be **z with a hat above it**.
> 
> You can see Figure 1 for an illustration of those symbols. Intuitively, symbols with a hat refer to augmented feature/embeddings, and symbols with a tilde refer to synthesized feature/embeddings.
> 
> I hope you can understand the symbols even though I admit they are a bit confusing:(. You are welcomed to ask any further questions.
> 
> Thanks again!

Thanks for your timely reply! I'd rather to say after post this issue, I found it as you pointed out. :)

Another question,  In Sec. 3.3, you described the objective of generator `J_gen` as eq.9, while in the [code](https://github.com/wzzheng/HDML/blob/master/main_npair.py#L126-L139), it seems different from your paper. Is that a problem?

**Comment by wzzheng** [comment]
Can you please be more specific about the differences so I can check out?

**Comment by wzzheng** [comment]
I believe it is our mistake. Thanks for pointing it out! I will modify the codes and relevant parameters.

**Comment by wanghao14** [comment]
@wzzheng When will you update the next arxiv version?

**Comment by wzzheng** [comment]
> @wzzheng When will you update the next arxiv version?

Hi, in one or two days. And thanks for pushing me :)
