### ISSUE TITLE
How to run the code for the triplet loss?

### ISSUE THREAD

**Issue by 7578lgg** [wzzheng/HDML#7]
Hi @wzzheng,

Thanks for your interesting paper and open sourcing the code.
I'm trying to use your method to synthetic negative samples via the triplet loss (eq. 12. ) in your paper , but I found the "main_npair.py" is only suit for 'Npairloss'. And it's useless if simply change the "FLAGS.LossType" to "triple-loss".  So I wonder how to run the code for triplet loss, and could you tell me how to change "main_npair.py" for triplet loss, or could you send a file like "main_triple.py" to me? 
Here is my gmail: 7578lgg@gmail.com And thank you so much!

**Comment by wzzheng** [comment]
Hello! I've uploaded a file named main_triplet.py which applies HDML to the triplet loss. You should also change the "FLAGS.LossType" to "Triplet" and "FLAGS.batch_size" to a number that is divided by 3 (like 120).

**Comment by 7578lgg** [comment]
> Hello! I've uploaded a file named main_triplet.py which applies HDML to the triplet loss. You should also change the "FLAGS.LossType" to "Triplet" and "FLAGS.batch_size" to a number that is divided by 3 (like 120).

Words cannot express my gratitude! :)
